version: '3.8'

services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ~/Certbot/cert:/etc/letsencrypt
      - ~/Certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email ryabtsev.a.p@yandex.ru --agree-tos -d certbot.fiwa-gik.ru
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.certbot.rule=Host(`certbot.fiwa-gik.ru`)"
      - "traefik.http.routers.certbot.entrypoints=web"
      - "traefik.http.routers.certbot.service=certbot-service@docker"
      - "traefik.http.services.certbot-service.loadbalancer.server.port=80"
