version: '3.8'

services:
  coturn:
    image: instrumentisto/coturn
    container_name: coturn
    restart: always
    network_mode: host  # Упрощает работу с портами
    volumes:
      - ./turnserver.conf:/etc/turnserver.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Монтируем весь каталог
    command: ["turnserver", "-c", "/etc/turnserver.conf"]
